Some instructions to note:
- This assignment contains three parts
    - numpy (15 questions) 
    - pandas (15 questions)
-
- write the code only in places indicated
- assign answers to the variables named as question numbers (otherwise assignment won't be evaluated)
- This assignment will be evaluated automatically, each question contains 1 mark
    - each question will be evaluated based on the value of the variable assigned to it
    - if the variable is not assigned, it will be considered as 0
    - if the variable is assigned to a wrong value, it will be considered as 0
    - if the variable is assigned to a correct value, it will be considered as 1

In [1]:
# import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Numpy Basics (15 marks)

In [2]:
# 1. Create a 1D array of numbers from 0 to 9

q1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(q1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# 2. Create a 3×3 numpy array of all True’s (~1 line)

q2 = np.ones((3, 3), dtype=bool)

print(q2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# 3. Given an array as input, print only odd numbers as output (~2 lines)

a = np.arange(10)
q3 = a[a % 2 != 0]

print(q3)

[1 3 5 7 9]


In [5]:
# 4. Convert a 1D array to a 2D array with 2 rows (~1 line)

e = np.arange(10)
q4 = e.reshape(2, -1)

print(q4)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
# 5. How to stack two arrays vertically? (~1 line)

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
q5 = np.vstack((a, b))

print(q5)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
# 6. How to generate custom sequences in numpy without hardcoding? (~1 line)
# sequence: [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

a = np.array([1,2,3])
q6 = np.concatenate((np.repeat(a, 3), np.tile(a, 3)))

print(q6)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [8]:
# 7. Get the common items between a and b (~1 line)

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
q7 = np.intersect1d(a, b)

print(q7)

[2 4]


In [9]:
# 8. From array a remove all items present in array b (~1 line)

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
q8 = np.setdiff1d(a, b)

print(q8)

[1 2 3 4]


In [10]:
# 9. Get all items between 5 and 10 from given array (~1 line)

a = np.array([2, 6, 1, 9, 10, 3, 27])
q9 = a[(a >= 5) & (a <= 10)]

print(q9)

[ 6  9 10]


In [11]:
# 10. Convert the function maxx that works on two scalars, to work on two arrays. (~1 line)

def maxx(x, y):
    """Get the maximum of two items"""
    return np.maximum(x, y)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
q10 = maxx(a, b)

print(q10)

[6 7 9 8 9 7 5]


In [12]:
# 11. Swap columns 1 and 2 in the array arr. (~1 line)

q11 = np.arange(9).reshape(3,3)
q11[:, [1, 0, 2]] = q11[:, [0, 1, 2]]

print(q11)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [13]:
# 12. Swap rows 1 and 2 in the array arr (~1 line)

q12 = np.arange(9).reshape(3,3)
q12[[1, 0, 2], :] = q12[[0, 1, 2], :]


print(q12)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [14]:
# 13. Reverse the rows of a 2D array arr (~1 line)

arr = np.arange(9).reshape(3,3)
q13 = np.flip(arr, axis=0)

print(q13)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [15]:
# 14. Reverse the columns of a 2D array arr (~1 line)

arr = np.arange(9).reshape(3,3)
q14 = arr[:, ::-1]

print(q14)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [16]:
# 15. Limit the number of items printed in python numpy array a to a maximum of 6 elements. (~1 line)

q15 = np.arange(15)
# code here
q15 = np.array_str(q15[:6])

print(q15)

[0 1 2 3 4 5]


### Pandas Basics (15 marks)

**Note:** Each question should use the original imported dataframe. 
**Do not modify the original dataframe.**

In [17]:
# 1. Read dataframe from file 'data.csv', (no index) into a variable called q1 (~1 line)

df =  pd.read_csv('data.csv')
q16 = df

In [18]:
# 2. Return the first 3 rows of the DataFrame df.

q17 = df.head(3)

In [19]:
# 3. Select just the 'name' and 'age' columns from the DataFrame df. (~1 line)

q18 =  df[['name', 'age']]

In [20]:
# 4. Select the data in rows [3, 4, 8] and in columns ['name', 'age', 'number_of_pets']. (~1 line)

q19 = df.loc[[3, 4, 8], ['name', 'age', 'number_of_pets']]

In [21]:
# 5. Select only the rows where the number of pets is greater than 3. (~1 line)

q20 = df.loc[df['number_of_pets'] > 3]

In [22]:
# 6. Select the rows where the age is missing, i.e. it is NaN. (~1 line)

q21 = df[df['age'].isnull()]

In [23]:
# 7. Select the rows where the student name is not Dan or Alice. (~1 line)

q22 =  df[~df['name'].isin(['Dan', 'Alice'])]

In [24]:
# 8. Select the rows the age is between 30 and 50 (inclusive). (~1 line)

q23 =  df.loc[(df['age'] >= 30) & (df['age'] <= 50)]

In [25]:
# 9. Find the total age of all students. (~1 line)

q24 = df['age'].sum()

In [26]:
# 10. Calculate the mean age of all students. (~1 line)

q25 = df['age'].mean()

In [27]:
# 11. Count the number of students. (~1 line)

q26 = len(df)

In [28]:
# 12. Sort the DataFrame first by the values in the 'age' in decending order, then by the value in the 'name' column in ascending order. (~1 line)

q27 = df.sort_values(['age', 'name'], ascending=[False, True])

In [29]:
# 13. Add a new column, 'course', that contains the value 'big data'. (~1 line)

df['course'] = 'big data'
q28 = df

In [30]:
# 14. Delete the 'number_of_pets' column from the DataFrame. (~1 line)

q29 = df.drop('number_of_pets', axis=1, inplace=True)

In [31]:
# 15. Delete the row where the age is missing. (~1 line)

q30 = df.dropna(subset=['age'])